config/routes.rb
Rails4::Application.routes.draw do
  
  get 'mashtags/about' => 'mashtags#about', :as => 'mashtags_about'
  resources :competitions

  get 'mashtags/facebook' => 'mashtags#facebook'
  post 'mashtags/facebook' => 'mashtags#facebook'

    get 'upload' => 'upload#index', :as => 'upload'
    post 'upload' => 'upload#index'

    get 'upload/mixcloud' => 'upload#mixcloud', :as => 'mixcloud'
    post 'upload/mixcloud' => 'upload#mixcloud', :as => 'mixcloud_post'

    get 'upload/soundcloud' => 'upload#soundcloud', :as => 'soundcloud'
    post 'upload/soundcloud' => 'upload#soundcloud', :as => 'soundcloud_post'

  resources :designs

  resources :mashtags

  get 'mashtags/:id/embed' => 'mashtags#embed'
  

  root 'canvas#index'

  post 'canvas' => 'canvas#index'
  get 'canvas' => 'canvas#index'

  get 'preferences' => 'canvas#preferences'
  get 'canvas/connect' => 'canvas#connect'

  get 'designs/:id/json' => 'designs#show', :defaults => { :format => 'json' }, :as => :json

  post 'facebook_page_tab' => 'facebook_page_tabs#create', :as => 'new_fb_page_tab'

  get 'mixcloud/search' => 'mixcloud#search'
  post 'mixcloud/search' => 'mixcloud#search', :as => 'search'

end

app/models/design.rb
class Design < ActiveRecord::Base
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  before_action :set_design, only: [:show, :edit, :update, :destroy]

  # GET /designs
  # GET /designs.json
  def index
    @designs = Design.all
  end

  # GET /designs/1
  # GET /designs/1.json
  def show
  end

  # GET /designs/new
  def new
    @design = Design.new
  end

  # GET /designs/1/edit
  def edit
  end

  # POST /designs
  # POST /designs.json
  def create
    @design = Design.new(design_params)

    # shopify(@design)

    respond_to do |format|
      if @design.save
        format.html { redirect_to @design, notice: 'Design was successfully created.' }
        format.json { render action: 'show', status: :created, location: @design }
      else
        format.html { render action: 'new' }
        format.json { render json: @design.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /designs/1
  # PATCH/PUT /designs/1.json
  def update
    respond_to do |format|
      if @design.update(design_params)
        format.html { redirect_to @design, notice: 'Design was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @design.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /designs/1
  # DELETE /designs/1.json
  def destroy
    @design.destroy
    respond_to do |format|
      format.html { redirect_to designs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_design
      @design = Design.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def design_params
      params.require(:design).permit(:image, :slug, :title, :description)
    end
end

app/helpers/designs_helper.rb
module DesignsHelper

end

app/views/designs/_form.html.erb
<%= form_for(@design) do |f| %>
  <% if @design.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@design.errors.count, "error") %> prohibited this design from being saved:</h2>

      <ul>
      <% @design.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/designs/edit.html.erb
<h1>Editing design</h1>

<%= render 'form' %>

<%= link_to 'Show', @design %> |
<%= link_to 'Back', designs_path %>

app/views/designs/index.html.erb
<h1>Listing designs</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Slug</th>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @designs.each do |design| %>
      <tr>
        <td><%= design.image %></td>
        <td><%= design.slug %></td>
        <td><%= design.title %></td>
        <td><%= design.description %></td>
        <td><%= link_to 'Show', design %></td>
        <td><%= link_to 'Edit', edit_design_path(design) %></td>
        <td><%= link_to 'Destroy', design, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Design', new_design_path %>

app/views/designs/new.html.erb
<h1>New design</h1>

<%= render 'form' %>

<%= link_to 'Back', designs_path %>

app/views/designs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @design.image %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @design.slug %>
</p>

<p>
  <strong>Title:</strong>
  <%= @design.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @design.description %>
</p>

<%= link_to 'Edit', edit_design_path(@design) %> |
<%= link_to 'Back', designs_path %>