config/routes.rb
Rails4::Application.routes.draw do
  
  get 'mashtags/about' => 'mashtags#about', :as => 'mashtags_about'
  resources :competitions

  get 'mashtags/facebook' => 'mashtags#facebook'
  post 'mashtags/facebook' => 'mashtags#facebook'

    get 'upload' => 'upload#index', :as => 'upload'
    post 'upload' => 'upload#index'

    get 'upload/mixcloud' => 'upload#mixcloud', :as => 'mixcloud'
    post 'upload/mixcloud' => 'upload#mixcloud', :as => 'mixcloud_post'

    get 'upload/soundcloud' => 'upload#soundcloud', :as => 'soundcloud'
    post 'upload/soundcloud' => 'upload#soundcloud', :as => 'soundcloud_post'

  resources :designs

  resources :mashtags

  get 'mashtags/:id/embed' => 'mashtags#embed'
  

  root 'canvas#index'

  post 'canvas' => 'canvas#index'
  get 'canvas' => 'canvas#index'

  get 'preferences' => 'canvas#preferences'
  get 'canvas/connect' => 'canvas#connect'

  get 'designs/:id/json' => 'designs#show', :defaults => { :format => 'json' }, :as => :json

  post 'facebook_page_tab' => 'facebook_page_tabs#create', :as => 'new_fb_page_tab'

  get 'mixcloud/search' => 'mixcloud#search'
  post 'mixcloud/search' => 'mixcloud#search', :as => 'search'

end

app/models/competition.rb
class Competition < ActiveRecord::Base
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :set_competition, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token  

  # GET /competitions
  # GET /competitions.json
  def index
    @competitions = Competition.all
  end

  # GET /competitions/1
  # GET /competitions/1.json
  def show
    @params = params
  end

  # GET /competitions/new
  def new
    @competition = Competition.new
  end

  # GET /competitions/1/edit
  def edit
  end

  # POST /competitions
  # POST /competitions.json
  def create
    @competition = Competition.new(competition_params)

    respond_to do |format|
      if @competition.save
        format.html { redirect_to @competition, notice: 'Competition was successfully created.' }
        format.json { render action: 'show', status: :created, location: @competition }
      else
        format.html { render action: 'new' }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /competitions/1
  # PATCH/PUT /competitions/1.json
  def update
    respond_to do |format|
      if @competition.update(competition_params)
        format.html { redirect_to @competition, notice: 'Competition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @competition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /competitions/1
  # DELETE /competitions/1.json
  def destroy
    @competition.destroy
    respond_to do |format|
      format.html { redirect_to competitions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_competition
      @competition = Competition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def competition_params
      params.require(:competition).permit(:title, :body, :css, :signed_request, :live)
    end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_form.html.erb
<%= form_for(@competition) do |f| %>
  <% if @competition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@competition.errors.count, "error") %> prohibited this competition from being saved:</h2>

      <ul>
      <% @competition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :css %><br>
    <%= f.text_area :css %>
  </div>

  <div class="field">
    <%= f.label :live %><br>
    <%= f.check_box :live %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/competitions/edit.html.erb
<h1>Editing competition</h1>

<%= render 'form' %>

<%= link_to 'Show', @competition %> |
<%= link_to 'Back', competitions_path %>

app/views/competitions/index.html.erb
<h1>Listing competitions</h1>
<br>

<%= link_to 'New Competition', new_competition_path %>

<br>
<hr/>
<br>

<ul>
<% @competitions.each do |competition| %>
  <li><%= link_to competition.title, competition %></li>
<% end %>
</ul>

<br>
<hr/>
<br>

<h3>Select a competition to connect to a facebook page</h3>
<br>

<form>
<%= collection_select(:competition, :id, @competitions, :id, :title, {:prompt => true}) %>
</form>

<br/>

<button id="fb" class="btn btn-large">Connect</button>


<div id="fb-root"></div>
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '263676013810410',
          status     : true,
          xfbml      : true
        });

        $('button#fb').on('click', function(){

          var comp = $('#competition_id').val();
          console.log(comp);


           FB.ui({
              method: 'pagetab',
              redirect_uri: '/competitions',
            }, function(response){

                var comp = $('#competition_id').val();
                console.log(comp);
                var page_id = Object.keys(response.tabs_added)[0];
                console.log(response);
                console.log(response.tabs_added);
                console.log(Object.keys(response.tabs_added)[0]);

                // ajax call to post facebook_page_id and competition.id to a new model
                $.ajax({
                  type: "POST",
                  url: "/facebook_page_tab",
                  data: { facebook_page_tab: { competition_id: comp, facebook_page_id: page_id } },
                  success: function() {
                    console.log('success');
                            },
                  dataType: "jsonp"
                });



                });

        });

       
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/all.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    </script>

app/views/competitions/new.html.erb
<h1>New competition</h1>

<%= render 'form' %>

<%= link_to 'Back', competitions_path %>

app/views/competitions/show.html.erb
<p class="hidden"><%= @params[:signed_request] %><br/>params = <%= @params %><br/>app_data = <%= @app_data %></p>

<p>
  <%= @competition.body.html_safe %>
</p>

<style type="text/css">
  <%= @competition.css.html_safe %>
</style>