config/routes.rb
Rails4::Application.routes.draw do
  
  get 'mashtags/about' => 'mashtags#about', :as => 'mashtags_about'
  resources :competitions

  get 'mashtags/facebook' => 'mashtags#facebook'
  post 'mashtags/facebook' => 'mashtags#facebook'

    get 'upload' => 'upload#index', :as => 'upload'
    post 'upload' => 'upload#index'

    get 'upload/mixcloud' => 'upload#mixcloud', :as => 'mixcloud'
    post 'upload/mixcloud' => 'upload#mixcloud', :as => 'mixcloud_post'

    get 'upload/soundcloud' => 'upload#soundcloud', :as => 'soundcloud'
    post 'upload/soundcloud' => 'upload#soundcloud', :as => 'soundcloud_post'

  resources :designs

  resources :mashtags

  get 'mashtags/:id/embed' => 'mashtags#embed'
  

  root 'canvas#index'

  post 'canvas' => 'canvas#index'
  get 'canvas' => 'canvas#index'

  get 'preferences' => 'canvas#preferences'
  get 'canvas/connect' => 'canvas#connect'

  get 'designs/:id/json' => 'designs#show', :defaults => { :format => 'json' }, :as => :json

  post 'facebook_page_tab' => 'facebook_page_tabs#create', :as => 'new_fb_page_tab'

  get 'mixcloud/search' => 'mixcloud#search'
  post 'mixcloud/search' => 'mixcloud#search', :as => 'search'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails4</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="">

<%= yield %>

</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48749308-1', 'floating-escarpment-5815.herokuapp.com');
  ga('send', 'pageview');

</script>

</body>
</html>

app/views/layouts/embed.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>#MashTag</title>
	    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%#= javascript_include_tag "mashtag" %>
		<%= csrf_meta_tags %>
        <meta name="description" content="#MashTag - Enter a Mixcloud username below for a mashup tagcloud of the music you love!">
        <meta name="viewport" content="width=device-width">
    </head>

    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
    

		<%= yield %>

</body>
</html>

app/views/layouts/mashtag.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>#MashTag</title>
	    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%#= javascript_include_tag "mashtag" %>
		<%= csrf_meta_tags %>
        <meta name="description" content="#MashTag - Enter a Mixcloud username below for a mashup tagcloud of the music you love!">
        <meta name="viewport" content="width=device-width">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
    </head>

    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
    <div class="navbar navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "#MashTag", mashtags_path, :class => "navbar-brand" %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class=""><%= link_to "About", mashtags_about_path %></li>
          </ul>
        </div><!--/.navbar-collapse -->
      </div>
    </div>

		<%= yield %>

		<footer>
		<div class="text-center">
		<p>&copy; #MashTag 2014</p>
		</div>
		</footer>

</body>
</html>